Fix CmsCommentsAccess cast (Java 8+)
With Java 8 the compilation breaks with an "incompatible types" error.

Error log follows:

````
alkacon-oamp/com.alkacon.opencms.v8.comments/src/com/alkacon/opencms/v8/comments/CmsCommentsAccess.java:1019: error: incompatible types: Object cannot be converted to Entry<String,String[]>
            for (Map.Entry<String, String[]> entry : CmsRequestUtil.createParameterMap(req.getParameterMap()).entrySet()) {
                                                                                                                      ^
Note: [...]/alkacon-oamp/com.alkacon.opencms.v8.comments/src/com/alkacon/opencms/v8/comments/CmsCommentsAccess.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error
:compileComAlkaconOpencmsV8CommentsJava FAILED
````